# Bellman Equations Programming Assignment

### Mukul Kumar Dhali
### University of Cumberland, School of Computer and Information Sciences
### PhDAI 830: Applied Machine Intelligence and Reinforcement Learning
### Professor Dr. Soamar Homsi​
### September 06, 2026


**Project description:** This notebook implements the Bellman Expectation Equation and Bellman Optimality Equation for Markov Decision Processes (MDPs).




## 1. Setup MDP Components
States, actions, transition probabilities, and rewards.

In [1]:
import numpy as np

n_states = 3
n_actions = 2
gamma = 0.9

P = np.array([
    [
        [0.8, 0.2, 0.0],
        [0.0, 1.0, 0.0]
    ],
    [
        [0.0, 0.5, 0.5],
        [0.0, 0.0, 1.0]
    ],
    [
        [0.0, 0.0, 1.0],
        [0.0, 0.0, 1.0]
    ]
])

R = np.array([
    [
        [1.0, 0.0, 0.0],
        [0.0, 2.0, 0.0]
    ],
    [
        [0.0, 1.0, 3.0],
        [0.0, 0.0, 4.0]
    ],
    [
        [0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0]
    ]
])

pi = np.array([
    [0.5, 0.5],
    [1.0, 0.0],
    [0.0, 1.0]
])

print("MDP Loaded.")

MDP Loaded.


## 2. Bellman Expectation Equation for V

In [2]:
def bellman_expectation_V(P, R, pi, gamma, V):
    n_states, n_actions, _ = P.shape
    V_new = np.zeros_like(V)
    for s in range(n_states):
        value = 0.0
        for a in range(n_actions):
            for s_next in range(n_states):
                value += pi[s, a] * P[s, a, s_next] * (R[s, a, s_next] + gamma * V[s_next])
        V_new[s] = value
    return V_new

V = np.zeros(n_states)
for i in range(10):
    V = bellman_expectation_V(P, R, pi, gamma, V)
    print(f"Iteration {i}: V = {V}")

Iteration 0: V = [1.4 2.  0. ]
Iteration 1: V = [2.984 2.9   0.   ]
Iteration 2: V = [4.04024 3.305   0.     ]
Iteration 3: V = [4.6391864 3.48725   0.       ]
Iteration 4: V = [4.9532221 3.5692625 0.       ]
Iteration 5: V = [5.11056171 3.60616812 0.        ]
Iteration 6: V = [5.187133   3.62277566 0.        ]
Iteration 7: V = [5.22366674 3.63024905 0.        ]
Iteration 8: V = [5.24085451 3.63361207 0.        ]
Iteration 9: V = [5.24885814 3.63512543 0.        ]


## 3. Bellman Expectation Equation for Q

In [3]:
def bellman_expectation_Q(P, R, pi, gamma, Q):
    n_states, n_actions, _ = P.shape
    Q_new = np.zeros_like(Q)
    for s in range(n_states):
        for a in range(n_actions):
            value = 0.0
            for s_next in range(n_states):
                next_value = np.sum(pi[s_next] * Q[s_next])
                value += P[s, a, s_next] * (R[s, a, s_next] + gamma * next_value)
            Q_new[s, a] = value
    return Q_new

Q = np.zeros((n_states, n_actions))
for i in range(10):
    Q = bellman_expectation_Q(P, R, pi, gamma, Q)
    print(f"Iteration {i}:\nQ =\n{Q}\n")

Iteration 0:
Q =
[[0.8 2. ]
 [2.  4. ]
 [0.  0. ]]

Iteration 1:
Q =
[[2.168 3.8  ]
 [2.9   4.   ]
 [0.    0.   ]]

Iteration 2:
Q =
[[3.47048 4.61   ]
 [3.305   4.     ]
 [0.      0.     ]]

Iteration 3:
Q =
[[4.3038728 4.9745   ]
 [3.48725   4.       ]
 [0.        0.       ]]

Iteration 4:
Q =
[[4.76791921 5.138525  ]
 [3.5692625  4.        ]
 [0.         0.        ]]

Iteration 5:
Q =
[[5.00878716 5.21233625]
 [3.60616812 4.        ]
 [0.         0.        ]]

Iteration 6:
Q =
[[5.12871469 5.24555131]
 [3.62277566 4.        ]
 [0.         0.        ]]

Iteration 7:
Q =
[[5.18683538 5.26049809]
 [3.63024905 4.        ]
 [0.         0.        ]]

Iteration 8:
Q =
[[5.21448488 5.26722414]
 [3.63361207 4.        ]
 [0.         0.        ]]

Iteration 9:
Q =
[[5.22746542 5.27025086]
 [3.63512543 4.        ]
 [0.         0.        ]]



## 4. Bellman Optimality Equation for V*

In [4]:
def bellman_optimality_V(P, R, gamma, V):
    n_states, n_actions, _ = P.shape
    V_new = np.zeros_like(V)
    for s in range(n_states):
        action_values = []
        for a in range(n_actions):
            value = 0.0
            for s_next in range(n_states):
                value += P[s, a, s_next] * (R[s, a, s_next] + gamma * V[s_next])
            action_values.append(value)
        V_new[s] = max(action_values)
    return V_new

V_star = np.zeros(n_states)
for i in range(10):
    V_star = bellman_optimality_V(P, R, gamma, V_star)
    print(f"Iteration {i}: V* = {V_star}")

Iteration 0: V* = [2. 4. 0.]
Iteration 1: V* = [5.6 4.  0. ]
Iteration 2: V* = [5.6 4.  0. ]
Iteration 3: V* = [5.6 4.  0. ]
Iteration 4: V* = [5.6 4.  0. ]
Iteration 5: V* = [5.6 4.  0. ]
Iteration 6: V* = [5.6 4.  0. ]
Iteration 7: V* = [5.6 4.  0. ]
Iteration 8: V* = [5.6 4.  0. ]
Iteration 9: V* = [5.6 4.  0. ]


## 5. Bellman Optimality Equation for Q*

In [5]:
def bellman_optimality_Q(P, R, gamma, Q):
    n_states, n_actions, _ = P.shape
    Q_new = np.zeros_like(Q)
    for s in range(n_states):
        for a in range(n_actions):
            value = 0.0
            for s_next in range(n_states):
                max_next = np.max(Q[s_next])
                value += P[s, a, s_next] * (R[s, a, s_next] + gamma * max_next)
            Q_new[s, a] = value
    return Q_new

Q_star = np.zeros((n_states, n_actions))
for i in range(10):
    Q_star = bellman_optimality_Q(P, R, gamma, Q_star)
    print(f"Iteration {i}:\nQ* =\n{Q_star}\n")

Iteration 0:
Q* =
[[0.8 2. ]
 [2.  4. ]
 [0.  0. ]]

Iteration 1:
Q* =
[[2.96 5.6 ]
 [3.8  4.  ]
 [0.   0.  ]]

Iteration 2:
Q* =
[[5.552 5.6  ]
 [3.8   4.   ]
 [0.    0.   ]]

Iteration 3:
Q* =
[[5.552 5.6  ]
 [3.8   4.   ]
 [0.    0.   ]]

Iteration 4:
Q* =
[[5.552 5.6  ]
 [3.8   4.   ]
 [0.    0.   ]]

Iteration 5:
Q* =
[[5.552 5.6  ]
 [3.8   4.   ]
 [0.    0.   ]]

Iteration 6:
Q* =
[[5.552 5.6  ]
 [3.8   4.   ]
 [0.    0.   ]]

Iteration 7:
Q* =
[[5.552 5.6  ]
 [3.8   4.   ]
 [0.    0.   ]]

Iteration 8:
Q* =
[[5.552 5.6  ]
 [3.8   4.   ]
 [0.    0.   ]]

Iteration 9:
Q* =
[[5.552 5.6  ]
 [3.8   4.   ]
 [0.    0.   ]]



## 6. AI Use Disclosure
AI assistance was used to help structure the notebook and generate example implementations. All code and explanations were reviewed and understood before inclusion.